// ===== TRACK SERVICE FORM =====
const trackForm = document.getElementById('trackForm');
if (trackForm) {
  trackForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    const btn = trackForm.querySelector('button[type="submit"]');
    const bookingId = document.getElementById('bookingId').value;

    btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Searching...';
    btn.disabled = true;

    try {
      const response = await fetch(`http://localhost:5000/api/bookings/${bookingId}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        }
      });

      const data = await response.json();

      if (response.ok) {
        document.getElementById('resultBookingId').textContent = data._id;
        document.getElementById('resultService').textContent = data.service;
        document.getElementById('resultVehicle').textContent = data.vehicle;
        document.getElementById('resultDate').textContent = new Date(data.date).toLocaleDateString();
        
        const statusBadge = document.getElementById('resultStatus');
        statusBadge.textContent = data.status.toUpperCase();
        
        // Set status color
        statusBadge.className = 'value status-badge';
        if (data.status === 'pending') {
          statusBadge.style.background = '#f59e0b';
        } else if (data.status === 'confirmed') {
          statusBadge.style.background = '#3b82f6';
        } else if (data.status === 'completed') {
          statusBadge.style.background = '#10b981';
        } else if (data.status === 'cancelled') {
          statusBadge.style.background = '#ef4444';
        }

        // Store booking data for PDF generation
        window.currentBooking = data;

        document.getElementById('trackingResult').style.display = 'block';
      } else {
        alert(data.message || 'Booking not found');
        document.getElementById('trackingResult').style.display = 'none';
      }
    } catch (error) {
      console.error('Error:', error);
      alert('Error tracking service. Please try again.');
      document.getElementById('trackingResult').style.display = 'none';
    } finally {
      btn.innerHTML = 'Track Service <i class="fas fa-search"></i>';
      btn.disabled = false;
    }
  });
}

// ===== GENERATE PDF REPORT =====
function generatePDF(booking) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(22);
  doc.setTextColor(14, 165, 233);
  doc.text('AutoCare Hub', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Service Report', 105, 30, { align: 'center' });
  
  // Add line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 35, 190, 35);
  
  // Add booking details
  doc.setFontSize(12);
  let y = 50;
  
  doc.setFontSize(14);
  doc.setTextColor(14, 165, 233);
  doc.text('Booking Details', 20, y);
  y += 10;
  
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Booking ID: ${booking._id}`, 20, y); y += 8;
  doc.text(`Service: ${booking.service}`, 20, y); y += 8;
  doc.text(`Vehicle: ${booking.vehicle}`, 20, y); y += 8;
  doc.text(`Date: ${new Date(booking.date).toLocaleDateString()}`, 20, y); y += 8;
  doc.text(`Status: ${booking.status.toUpperCase()}`, 20, y); y += 15;
  
  // Add customer details
  doc.setFontSize(14);
  doc.setTextColor(14, 165, 233);
  doc.text('Customer Details', 20, y);
  y += 10;
  
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Name: ${booking.name}`, 20, y); y += 8;
  doc.text(`Email: ${booking.email}`, 20, y); y += 8;
  doc.text(`Phone: ${booking.phone}`, 20, y); y += 15;
  
  // Add message if exists
  if (booking.message) {
    doc.setFontSize(14);
    doc.setTextColor(14, 165, 233);
    doc.text('Additional Notes', 20, y);
    y += 10;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    const splitMessage = doc.splitTextToSize(booking.message, 170);
    doc.text(splitMessage, 20, y);
  }
  
  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by AutoCare Hub', 105, 280, { align: 'center' });
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' });
  
  // Save PDF
  doc.save(`autocare-report-${booking._id}.pdf`);
}
